import type { HostCapabilities } from "../../../core/src/types/host.js";

export const capabilityMatrix: Record<string, HostCapabilities> = {
  pi: {
    nativeSkills: true,
    slashCommands: true,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: true,
    canReadFiles: true,
    canWriteFiles: true,
    canRunCommands: true,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
  codex: {
    nativeSkills: true,
    slashCommands: false,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: true,
    canReadFiles: true,
    canWriteFiles: true,
    canRunCommands: true,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
  opencode: {
    nativeSkills: true,
    slashCommands: false,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: true,
    canReadFiles: true,
    canWriteFiles: true,
    canRunCommands: true,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
  openclaw: {
    nativeSkills: false,
    slashCommands: false,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: true,
    canReadFiles: false,
    canWriteFiles: false,
    canRunCommands: false,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
  hermes: {
    nativeSkills: true,
    slashCommands: true,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: true,
    canReadFiles: true,
    canWriteFiles: true,
    canRunCommands: true,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
  chatgpt: {
    nativeSkills: false,
    slashCommands: false,
    systemPrompt: true,
    projectInstructions: true,
    repoAware: false,
    canReadFiles: false,
    canWriteFiles: false,
    canRunCommands: false,
    canUseBrowser: false,
    supportsSequences: true,
    supportsStateInjection: true,
  },
};
